name: Back Mesure coverage

on:
  [push]

env: 
  INPUT_JACOCO-CSV-FILE: back/target/site/jacoco/

jobs:
  coverage_job:
      build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven
        - name: Build with Maven
          run: mvn -B test --file back/pom.xml
        - name: Report into branch "report"
          run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            git pull
            git checkout report
            git add -A -f back/target/site/jacoco
            git commit -m "new report"
            git push
        - name: Generate JaCoCo badge
          id: jacoco
          uses: cicirello/jacoco-badge-generator@v2
          with:
            badges-directory: badges
            generate-branches-badge: true
            generate-summary: true
            jacoco-csv-file: back/target/site/jacoco/jacoco.csv
            
  sonar_job:
     build:
        runs-on: ubuntu-latest
        needs: coverage_job
        
        steps:
          - uses: actions/checkout@v4
          - name: Cache SonarCloud packages
          uses: actions/cache@v3

