name: Front coverage

on:
  [push]

jobs:
  build-and-test-web-with-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node for Web project
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: front/package-lock.json
    - name: Install dependencies for front project
      run: npm ci
      working-directory: front
      
    - name: Build front project
      run: npm run build --if-present
      working-directory: front
      
    - name: Run test for front project
      run: npm run test:prod
      working-directory: front
      

    - name: Report into branch "report"
      run: |
        //git config --global
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git pull
        git checkout report
        git add ./front/coverage/bobapp/
        git commit -m "[Front] Report ${{ github.event.repository.updated_at}}"

    - name: Push
      uses: ad-m/github-push-action@master