name: Web CI/CD Workflowon:
  push:
    branches:
      - developpe
    paths:
      - 'front/**'
  pull_request:
    branches:
      - main
    paths:
      - 'front/**'jobs:
  build-and-test-web-with-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node for Web project
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: front/package-lock.json
    - name: Install dependencies for front project
      run: npm ci
      working-directory: front    
    - name: Build front project
      run: npm run build --if-present
      working-directory: front    
    - name: Run test with coverage
      working-directory: front
      run: npm run test -- --code-coverage --browsers=ChromeHeadless --watch=false    - name: Commit Coverage Report
      run: |
        git config --global user.email "mvouyorick@gmail.com"
        git config --global user.name "GitHub Actions"
        git fetch --all
        git checkout report
        git pull origin report
        mkdir -p report/front
        cp -r front/coverage/bobapp/* ./coverage-repport/front
        git add ./coverage-repport/front
        git commit -m "Update Coverage Reports"
        git push origin coverage-reports
    env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
