name: Node.js CI

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./front/

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for lock file
      run: |
        if [ ! -f package-lock.json ]; then
          echo "Error: package-lock.json not found in  directory"
          exit 1
        else
          echo "package-lock.json found in ./front directory"
        fi
      shell: bash

    - name: Display node version
      run: node --version

    - name: Display npm version
      run: npm --version

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test

    - name: Run lint
      run: npm run lint